import express from "express";
import userRouter from "./modules/user/routes/userRoutes.js";
import googleRouter from "./modules/google/routes/google.routes.js";
import courseRouter from "./modules/courses/routes/course.routes.js";
import moduleRouter from "./modules/module/routes/module.routes.js";
import lessionRouter from "./modules/lession/routes/routes.js";
import paymentRouter from "./modules/dummyPayment/routes/dummyRoutes.js";
const router = express.Router();
router.use("/api/v1/user", userRouter);
router.use("/api/v1/google", googleRouter);
router.use("/api/v1/module", moduleRouter);
router.use("/api/v1/course", courseRouter);
router.use("/api/v1/lession", lessionRouter);
router.use("/api/v1/payment", paymentRouter);
export default router;
